import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { TRPCReactProvider } from "@/trpc/client";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that wraps the application with TRPCReactProvider and applies the Inter font and antialiasing to the document body.
 *
 * @param children - The React nodes to render inside the application's <body>.
 * @returns A React element containing the HTML document structure (<html> and <body>) wrapped by `TRPCReactProvider`.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body
          className={`${inter.className} antialiased`}
        >
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}